import './style.css';
import { analytics, email, results } from './adapters';
import { certifications } from './data/certifications';
import { domains, questions } from './data/questions';
import { scaledScore, scoreAnswer, shuffleOptions } from './lib/quiz';

const footer = `<footer><p>Blueprint is an independent study resource. It is not affiliated with, endorsed by, or sponsored by Anthropic. Claude and the Claude certification names are Anthropic's; they are used here only to say which exams these materials are for. Every practice question on this site is original material written against each exam's publicly published blueprint — none of it is real, leaked, or recalled exam content.</p></footer>`;
const shell = (content: string) => `<header><a class="brand" href="/">Blueprint <small>by Holy Shifted</small></a><nav><a href="/exam/">Exam</a><a href="/framework/">Framework</a><a href="/cheat-sheet/">Cheat sheet</a><a href="/quiz/">Practice exam</a></nav></header><main>${content}</main>${footer}`;
const tiles = certifications.map((item) => `<article class="tile ${item.state}"><span>${item.code}</span><h3>${item.name}</h3><p>${item.audience}</p>${item.state === 'available' ? `<p>${item.meta}</p><a class="button" href="${item.href}">Start the practice exam</a>` : `<b>Not written yet</b><p>I've only sat the Developer exam. A practice set for this one goes up when I've done the work properly — no date promised.</p>`}</article>`).join('');
const placeholder = (title: string, text: string) => shell(`<section class="prose"><h1>${title}</h1><p>${text}</p><p>Long-form study content is being prepared. This independent resource uses original material based on the public blueprint.</p></section>`);
const root = document.querySelector<HTMLDivElement>('#app')!;
const path = location.pathname;
if (path === '/' || path === '/index.html') root.innerHTML = shell(`<section class="hero"><p class="eyebrow">Free and independent</p><h1>Practice the blueprint, not a dump.</h1><p>Free practice exams for the Claude certifications — original questions written to each exam's published blueprint, with every answer option explained.</p><a class="button" href="/quiz/">Start the practice exam</a></section><section><h2>What this is</h2><p class="prose">Blueprint is a free, independent study resource for Anthropic's Claude certification exams. It is not affiliated with Anthropic, and it does not contain real exam questions. The practice material is written from scratch against the published blueprint.</p></section><section><h2>Practice exams</h2><div class="tiles">${tiles}</div></section>`);
else if (path.startsWith('/exam')) root.innerHTML = placeholder('CCDV-F exam overview', 'A placeholder overview for the original 53-question practice set and its eight domains.');
else if (path.startsWith('/framework')) root.innerHTML = placeholder('How to think about it', 'A placeholder framework for working methodically through scenario-based questions.');
else if (path.startsWith('/cheat-sheet')) root.innerHTML = placeholder('CCDV-F cheat sheet', 'This sheet is my own compression of the CCDV-F blueprint. It is not an answer key and it is not affiliated with Anthropic.');
else if (path.startsWith('/privacy')) root.innerHTML = placeholder('Privacy', 'Nothing is collected for the quiz itself. An email is sent only when you explicitly choose to subscribe.');
else if (path.startsWith('/quiz')) mountQuiz();
else root.innerHTML = shell(`<section class="prose"><h1>There's nothing at this address.</h1><a class="button" href="/">Back to the practice exams</a></section>`);
analytics.pageView(path);

type Saved = { index: number; answers: Record<string, string[]>; startedAt: string; order: Record<string, string[]> };
const key = 'blueprint-ccdvf-attempt-v1';
function mountQuiz() {
 const saved: Saved | null = JSON.parse(localStorage.getItem(key) || 'null');
 let state: Saved = saved || { index: 0, answers: {}, startedAt: new Date().toISOString(), order: Object.fromEntries(questions.map((q) => [q.id, shuffleOptions(q.options).map((o) => o.id)])) };
 let revealed = Boolean(state.answers[questions[state.index]?.id]);
 const persist = () => localStorage.setItem(key, JSON.stringify(state));
 const render = () => {
  const question = questions[state.index];
  if (!question) return renderResults();
  const selected = new Set(state.answers[question.id] || []);
  const choices = state.order[question.id].map((id) => question.options.find((o) => o.id === id)!).map((option) => `<label class="option ${revealed ? (option.correct ? 'correct' : 'incorrect') : ''}"><input ${question.type === 'single' ? 'type="radio" name="answer"' : 'type="checkbox"'} value="${option.id}" ${selected.has(option.id) ? 'checked' : ''} ${revealed ? 'disabled' : ''}><span>${option.text}</span>${revealed ? `<small><strong>${option.correct ? '✓ Correct' : '× Incorrect'}</strong> ${option.explanation}${selected.has(option.id) ? ' <em>Your selection</em>' : ''}</small>` : ''}</label>`).join('');
  root.innerHTML = shell(`<section class="quiz"><p class="eyebrow">Question ${state.index + 1} of 53 · ${domains.find((d) => d.id === question.domainId)?.name || question.domainId}</p><progress value="${state.index + 1}" max="53"></progress><p id="timer" class="muted">Elapsed time: 0m</p><h1>${question.stem}</h1>${question.type === 'multi' ? '<p>Select all that apply.</p>' : ''}<form id="question-form">${choices}<div class="actions">${revealed ? `<p>${scoreAnswer(question.options, [...selected]) ? 'You got this one.' : 'Not this one.'}</p><button>${state.index === questions.length - 1 ? 'See your results' : 'Next question'}</button>` : '<button disabled>Check answer</button>'}</div></form><button class="link" id="reset">Reset and start over</button></section>`);
  const timer = document.querySelector('#timer')!; const tick = () => timer.textContent = `Elapsed time: ${Math.floor((Date.now() - new Date(state.startedAt).getTime()) / 60000)}m`; tick();
  document.querySelectorAll<HTMLInputElement>('input').forEach((input) => input.addEventListener('change', () => { const values = [...document.querySelectorAll<HTMLInputElement>('input:checked')].map((item) => item.value); state.answers[question.id] = values; persist(); const button = document.querySelector<HTMLButtonElement>('.actions button')!; button.disabled = values.length === 0; }));
  document.querySelector('#question-form')!.addEventListener('submit', (event) => { event.preventDefault(); if (!revealed) { revealed = true; persist(); render(); } else { state.index += 1; revealed = Boolean(state.answers[questions[state.index]?.id]); persist(); render(); } });
  document.querySelector('#reset')!.addEventListener('click', () => { localStorage.removeItem(key); state = { index: 0, answers: {}, startedAt: new Date().toISOString(), order: Object.fromEntries(questions.map((q) => [q.id, shuffleOptions(q.options).map((o) => o.id)])) }; revealed = false; render(); });
 }; render();
 function renderResults() { const correct = questions.filter((q) => scoreAnswer(q.options, state.answers[q.id] || [])).length; const score = scaledScore(correct, 53); root.innerHTML = shell(`<section class="quiz"><h1>${score >= 720 ? "You'd have passed this one." : 'Not there yet.'}</h1><p>${score} out of 1000 on this practice set. The real exam passes at 720.</p><p class="muted">This is a practice set, not a predictor. The real exam is scaled and equated; this number is just your percentage, weighted by domain.</p><h2>Where you lost points</h2>${domains.map((d) => { const qs = questions.filter((q) => q.domainId === d.id); const got = qs.filter((q) => scoreAnswer(q.options, state.answers[q.id] || [])).length; return `<p>${d.name} — ${got}/${qs.length || d.questionCount}</p>`; }).join('')}<h2>Want the next one?</h2><p>I'm writing practice sets for the other three Claude certifications. Leave an email and I'll send one message when the next one is live. Nothing else, ever.</p><form id="email-form"><label>Email <input type="email" required placeholder="you@example.com"></label><label><input type="checkbox" required> Email me when a new practice exam goes up. I can unsubscribe from any message.</label><button>Send it to me</button><p id="email-message" aria-live="polite"></p></form><button class="link" id="retake">Retake the exam</button></section>`); results.submitAttempt({ schemaVersion: 1, attemptId: crypto.randomUUID(), clientId: localStorage.getItem('blueprint-client') || crypto.randomUUID(), startedAt: state.startedAt, completedAt: new Date().toISOString(), completed: true, scaledScore: score, rawCorrect: correct, itemCount: 53, answers: questions.map((q) => ({ questionId: q.id, correct: scoreAnswer(q.options, state.answers[q.id] || []), selectedOptionIds: state.answers[q.id] || [], elapsedMs: 0 })) }); document.querySelector('#email-form')!.addEventListener('submit', async (e) => { e.preventDefault(); const form = e.currentTarget as HTMLFormElement; const address = form.querySelector<HTMLInputElement>('input[type=email]')!.value; const response = await email.subscribe({ schemaVersion: 1, email: address, consent: true, consentText: 'Email me when a new practice exam goes up. I can unsubscribe from any message.', source: 'quiz-result-ccdvf', submittedAt: new Date().toISOString() }); document.querySelector('#email-message')!.textContent = response.ok ? "Done. You'll hear from me once, when the next set is live." : "That didn't go through. Try again in a moment."; }); document.querySelector('#retake')!.addEventListener('click', () => { localStorage.removeItem(key); location.reload(); }); }
}
